import type { Metadata } from "next";
import "./globals.css";
import {
  ClerkProvider,
  SignedIn,
  SignUpButton,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Finance Tracker App",
  description: "Generated by dabs",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className="bg-gradient-to-br from-blue-400 via-green-500 to-indigo-600">

          <div className="flex justify-end p-4 mr-4">
            <SignedOut>
              <SignUpButton mode="modal" />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </div>
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
